app/config/routes.rb
Rails.application.routes.draw do
  resources :vtubers, only: [:index, :new, :create, :show, :destroy, :update, :edit] do
    resources :videos, only: [:index]
  end
  root 'vtubers#index'
end

app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/app/models/video.rb
class Video < ApplicationRecord
  belongs_to :vtuber
end

app/app/models/vtuber.rb
class Vtuber < ApplicationRecord
    validates :name, presence: true
    validates :subscribers, presence: true
    validates :superchats, presence: true

    mount_uploader :avatar, AvatarUploader

    has_many :videos
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/app/controllers/videos_controller.rb
class VideosController < ApplicationController
    def index
        @vtuber = Vtuber.find(params[:vtuber_id])
        @videos = @vtuber.videos
    end
end

app/app/controllers/vtubers_controller.rb
class VtubersController < ApplicationController
  before_action :set_vtuber, only: [:edit, :update, :show, :destroy]
  
  def index
    @vtubers = Vtuber.all
    @total_superchats = @vtubers.sum(:superchats)
  end

  def new
    @vtuber = Vtuber.new
  end
  
  def create
    @vtuber = Vtuber.new(vtuber_params)

    if @vtuber.save
      redirect_to @vtuber, notice: '追加できました!'
    else
      redirect_to new_vtuber_path, alert: '作成に失敗しました。未入力の項目があります。'
    end
  end

  def show
  end

  def destroy
    @vtuber.destroy
    redirect_to vtubers_path, notice:'削除しました'
  end
  
  def edit
  end

  def update
    if @vtuber.update(vtuber_params)
      redirect_to @vtuber, notice: '変更できました!'
    else
      redirect_to edit_vtuber_path(@vtuber), alert: '変更に失敗しました。未入力の項目があります。'
    end
  end

  private
    def set_vtuber
      @vtuber = Vtuber.find(params[:id])
    end
    
    def vtuber_params
      params.require(:vtuber).permit(:name, :subscribers, :superchats, :avatar, :remove_avatar, :youtube_views, :company, :registered_day, :link_to_channel)
    end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/scflds_helper.rb
module ScfldsHelper
end

app/app/helpers/videos_helper.rb
module VideosHelper
end

app/app/helpers/vtubers_helper.rb
module VtubersHelper
end

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppContainer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/app/views/videos/index.html.erb
<h1>Videos index</h1>
<% @videos.each do |video| %>
<div class="card">
    <div class="image-container">
        <%= image_tag("/videos/#{video.id}.jpg") %>
    </div>
    <div>
        <p class="title"><%= video.title %></p>
        <% if video.views? %>
        <p><%= video.views.to_s(:delimited) %> 回視聴</p>
        <% end %>
        <% if video.likes? %>
        <p><%= video.likes.to_s(:delimited) %> Likes</p>
        <% end %>
        <% if video.published_day? %>
        <p><%= video.published_day %> に公開済み</p>
        <% end %>
    </div>
    <%= link_to '', video.url, class: "card-link" %>
</div>
<% end %>

<%= link_to 'Vtuberの詳細ページへ戻る', vtuber_path(@vtuber.id) %>

app/app/views/vtubers/_form.html.erb
<%= form_with(model: vtuber, local: true) do |form| %>
<div class="field">
  <% unless vtuber.avatar? %>
  <p>↓画像をアップロードできます!</p>
  <%= form.file_field :avatar %>
  <% end %>

  <% if vtuber.avatar? %>
  <%= link_to(image_tag(@vtuber.avatar.thumb.url, alt: '画像'), @vtuber.avatar.url, target: '_blank') if @vtuber.avatar? %>
  <div>
    <%= label_tag :remove_avatar do %>
    画像を削除します
    <%=  form.check_box :remove_avatar %>
    <% end %>
  </div>
  <% end %>
</div>

<div class="field">
  <%= form.label :name, '名前' %>
  <%= form.text_field :name %>
</div>

<div class="field">
  <%= form.label :subscribers, 'チャンネル登録者数' %>
  <%= form.number_field :subscribers, step: "0.1" %>
</div>

<div class="field">
  <%= form.label :superchats, '累計スパチャ額' %>
  <%= form.number_field :superchats %>
</div>

<div class="field">
  <%= form.label :youtube_views, 'チャンネル視聴回数' %>
  <%= form.number_field :youtube_views %>
</div>

<div class="field">
  <%= form.label :company, '所属事務所' %>
  <%= form.select :company, {'ホロライブ': 'ホロライブ', 'にじさんじ': 'にじさんじ', '無所属': '無所属'}, { include_blank: '選択してください'}, { class: 'form-control' } %>
</div>

<div class="field">
  <%= form.label :registered_day, 'チャンネル開設日' %>
  <%= form.date_select :registered_day, include_blank: true, class: 'form-control' %>
</div>

<div class="field">
  <%= form.label :link_to_channel, 'Youtube公式チャンネルのリンク' %>
  <%= form.text_field :link_to_channel %>
</div>

<div class="actions">
  <%= form.submit '送信' %>
</div>
<% end %>

app/app/views/vtubers/edit.html.erb
<p id="alert"><%= alert %></p>

<h1>編集画面</h1>

<div>
    <%= render 'form', vtuber: @vtuber %>
</div>

<div>
    <%= link_to '詳細へ戻る', @vtuber %>
</div>

app/app/views/vtubers/index.html.erb
<p id="notice"><%= notice %></p>

<div class="home-section">
    <h1>▷Vtuber図鑑</h1>
    <p>Who is the MOST super chatted ? </p>
</div>
<div class="index-content">
    <div class="stats-card">
        <p class="title">Total Stats</p>
        <div class="stat-items">
            <div class="stat-item">
                <p class="number"><%= @vtubers.count %></p>
                <p class="indicator">Vtubers</p>
            </div>
            <div class="stat-item">
                <p class="number">¥<%= @total_superchats.to_s(:delimited) %></p>
                <p class="indicator">Superchats</p>
            </div>
        </div>
    </div>
    <div class="cards-list">
        <div class="cards-list-header">
            <div class="title">
                <p>VTUBERS BOARD</p>
            </div>
            <div class="button-wrapper">
                <div class="button-container">
                    <%= link_to '+ Vtuberを追加する!', new_vtuber_path, class: "button-link button-link__red" %>
                </div>
            </div>
        </div>
        <% @vtubers.each do |vtuber| %>
        <div class="card">
            <%= image_tag(vtuber.avatar.thumb.url, alt: "Vtuberの画像", class: "vtuber-image") if vtuber.avatar? %>
            <div>
                <p class="title"><%= vtuber.name %></p>
                <p class="subtitle">チャンネル登録者数: <%= vtuber.subscribers %>万人</p>
                <% if vtuber.superchats? %>
                <p class="subtitle">累計スパチャ額: <%= vtuber.superchats.to_s(:delimited) %>円</p>
                <% else %>
                <p class="subtitle">累計スパチャ額: 円</p>
                <% end %>
            </div>
            <%= link_to '', vtuber, class:"card-link" %>
        </div>
        <% end %>
    </div>
</div>

app/app/views/vtubers/new.html.erb
<p id="alert"><%= alert %></p>

<h1>Vtuberを追加する!</h1>
<div>
  <%= render 'form', vtuber: @vtuber %>
</div>

<%= link_to '一覧へ戻る', vtubers_path %>

app/app/views/vtubers/show.html.erb
<p id="notice"><%= notice %></p>


<div class="detail-content">
    <div class="info">
        <div class="info-heder">
            <div class="info-header-left">
                <div class="button-container">
                    <%= link_to '< 一覧へ戻る', vtubers_path, class: "button-link" %>
                </div>
            </div>
            <div class="info-header-right">
                <div class="button-container">
                    <%= link_to '編集する', edit_vtuber_path, class: "button-link button-link__red" %>
                </div>
                <div class="button-container">
                    <%= link_to '削除する', @vtuber, method: :delete, data: { confirm: 'Are you sure?' }, class: "button-link" %>
                </div>
            </div>
        </div>
        <div class="info-content">
            <div class="image-container">
                <%= image_tag(@vtuber.avatar.url, alt: "Vtuberの画像", :width => "100%", class: "vtuber-image") if @vtuber.avatar? %>
            </div>
            <div class="text-container">
                <p class="title"><%= @vtuber.name %></p>
                <p class="subtitle">チャンネル登録者数</p>
                <p class="number"><%= @vtuber.subscribers %> 万人</p>
                <% if @vtuber.superchats? %>
                <p class="subtitle">累計スパチャ額</p>
                <p class="number">¥ <%= @vtuber.superchats.to_s(:delimited) %></p>
                <% end %>
                <% if @vtuber.youtube_views? %>
                <p class="subtitle">チャンネル視聴回数</p>
                <p class="number"><%= @vtuber.youtube_views.to_s(:delimited) %> 回</p>
                <% end %>
                <% unless @vtuber.company == "" %>
                <p class="subtitle">所属事務所</p>
                <p class="number"><%= @vtuber.company %></p>
                <% end %>
                <% if @vtuber.registered_day? %>
                <p class="subtitle">チャンネル登録日</p>
                <p class="number"><%= @vtuber.registered_day %></p>
                <% end %>
                <% unless @vtuber.link_to_channel == "" %>
                <%= link_to 'Youtube公式チャンネルはこちら', @vtuber.link_to_channel %>
                <% end %>
            </div>
        </div>
    </div>
    <div class="movies">
        <div class="cards-list">
            <div class="cards-list-header">
                <div class="title">
                    <%= link_to '> More videos', vtuber_videos_path(@vtuber.id), class: "link" %>
                </div>
            </div>
            <% @vtuber.videos.each do |video| %>
            <div class="card">
                <div class="image-container">
                    <%= image_tag("/videos/#{video.id}.jpg") %>
                </div>
                <div>
                    <p class="title"><%= video.title %></p>
                </div>
                <%= link_to '', video.url, class: "card-link" %>
            </div>
            <% end %>
        </div>
    </div>
    <div class="nav">
        <%= link_to '< 一覧へ戻る', vtubers_path %>
    </div>
</div>